apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-webapp-deploy
  name: nginx-webapp-svc
spec:
  ports:
  - port: {{ .Values.service.nginxWebappSvc.port }}
    protocol: TCP
    targetPort: {{ .Values.service.nginxWebappSvc.port }}
  selector:
    app: nginx-webapp-deploy
  type: {{ .Values.service.nginxWebappSvc.type }}
status:
  loadBalancer: {}